name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'bicep/**'
      - 'scripts/**'
      - '.github/workflows/deploy-infrastructure.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'bicep/**'
      - 'scripts/**'
      - '.github/workflows/deploy-infrastructure.yml'
  workflow_dispatch:
    inputs:
      resourceGroupName:
        description: 'Azure Resource Group Name'
        required: true
        default: 'nostria'
      location:
        description: 'Azure Location'
        required: true
        default: 'westeurope'
      relayCount:
        description: 'Number of relay instances to deploy'
        required: true
        default: '1'
      mediaCount:
        description: 'Number of media instances to deploy'
        required: true
        default: '1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up Azure PowerShell module
      #   uses: azure/powershell@v2
      #   with:
      #     azPSVersion: 'latest'

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Infrastructure
        uses: azure/powershell@v2
        with:
          inlineScript: |
            $resourceGroupName = "${{ github.event.inputs.resourceGroupName || 'nostria' }}"
            $location = "${{ github.event.inputs.location || 'westeurope' }}"
            $relayCount = "${{ github.event.inputs.relayCount || '1' }}"
            $mediaCount = "${{ github.event.inputs.mediaCount || '1' }}"
            
            Write-Host "Deploying infrastructure to resource group: $resourceGroupName in location: $location"
            Write-Host "Relay Count: $relayCount, Media Count: $mediaCount"
            
            ./scripts/deploy.ps1 -ResourceGroupName $resourceGroupName -Location $location -RelayCount $relayCount -MediaCount $mediaCount
          azPSVersion: 'latest'
          
      - name: Log Deployment Results
        shell: pwsh
        run: |
          $resourceGroupName = "${{ github.event.inputs.resourceGroupName || 'nostria' }}"
          Write-Host "Deployment to $resourceGroupName completed"
          
          # Get deployment status using Azure CLI
          $deployments = az deployment group list --resource-group $resourceGroupName --query "[?contains(name, 'nostria-deployment')].{Name:name, Status:properties.provisioningState}" --output json | ConvertFrom-Json
          $latestDeployment = $deployments | Sort-Object Name -Descending | Select-Object -First 1
          
          if ($latestDeployment) {
            Write-Host "Latest deployment: $($latestDeployment.Name), status: $($latestDeployment.Status)"
            
            if ($latestDeployment.Status -eq "Succeeded") {
              Write-Host "✅ Deployment succeeded"
            } else {
              Write-Host "❌ Deployment failed or is still in progress"
              exit 1
            }
          } else {
            Write-Host "❌ No deployment found"
            exit 1
          }
