name: Build and Deploy Discovery App

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'discovery/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./discovery
        push: true
        tags: ghcr.io/nostria-app/discovery:${{ github.sha }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'discovery'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ghcr.io/nostria-app/discovery:${{ github.sha }}